language: ruby
bundler_args: --without development
before_install:
    - git submodule update --init --recursive
script: "bundle exec rake build"
rvm:
    - 1.9.3
gemfile:
    - Gemfile
branches:
    only:
        - master
        - develop
